// CH Vue/src/App.vue
<template>
    <div class="container">
      <h1>Notes Application</h1>
      <div class="row">
        <div className="col-3">
          <CategoryList />
          <NewCategory />
        </div>
        <div className="col-9">
          <Board /> 
        </div>     
      </div>
    </div>
</template>

<script>
import CategoryList from './components/CategoryList';
import NewCategory from './components/NewCategory';
import Board from './components/Board';

export default {
  name: 'app',
  components: {
    CategoryList,
    NewCategory,
    Board
  }
}
</script>

// CH Svelte/src/App.svelte
<div class="container">
  <h1>Notes Application</h1>
  <div class="row">
    <div class="col-3">
      <CategoryList />
      <NewCategory />
    </div>
    <div class="col-9">
      <Board /> 
    </div>     
  </div>
</div>

<script>
import CategoryList from './CategoryList.svelte';
import NewCategory from './NewCategory.svelte';
import Board from './Board.svelte';
</script>
