// CH Vue/src/components/Board.vue
<template>
    <div>
      <div class="row">
        <button 
         type="button"
         class="btn btn-primary" 
         @click="openCreateNote">
          Add
        </button>
      </div>
      <EditNote />
      <div class="row">
        <Note 
         v-for="note in notes" 
         :note="note" 
         :key="note.id" />
      </div>
    </div>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex';

import EditNote from './EditNote';
import Note from './Note';

export default {
  computed: {
    ...mapGetters([
      'notes'
    ])
  },
  methods: {
    ...mapMutations([
        'openCreateNote'
    ])
  },
  components: {
    EditNote,
    Note
  } 
}
</script>

// CH Svelte/src/Board.svelte
<div>
  <div class="row">
    <button 
     type="button"
     class="btn btn-primary"
     on:click={ui.openCreateNote}
    >
      Add
    </button>
  </div>
  <EditNote />
  <div class="row">
    {#each $filteredNotes as note}
      <Note note={note} />
    {/each}
  </div>
</div>

<script>
import EditNote from './EditNote.svelte';
import Note from './Note.svelte';

import notes from './stores/note.js';
import ui from './stores/ui.js';
import filteredNotes from './stores/filteredNotes';

notes.loadNotes();
</script>
