// CH Vue/src/components/NewCategory.vue
<template>
    <form>
        <div className="form-group">
        <input 
            type="text" 
            className="form-control"
            v-model="title" 
        />
        </div>
        <div v-if="title !== ''" >
            <button 
                type="button"
                className="btn btn-primary"
                @click="addCategoryAndClear">
                Add
            </button>
        </div>
    </form>
</template>

<script>
import { mapActions } from 'vuex';

export default {
data(){
    return {
        title: '',
    }
},
methods: {
    ...mapActions([
        'addCategory'
    ]),
    addCategoryAndClear(){
        this.addCategory(this.title);
        this.title = '';
    }
}
}
</script>

// CH Svelte/src/NewCategory.svelte
<form>
    <div class="form-group">
    <input 
     type="text" 
     class="form-control"
     bind:value={title} 
    />
    </div>
    {#if title !== ''}
    <div>
        <button 
         type="button"
         class="btn btn-primary"
         on:click={addCategoryAndClear}>
            Add
        </button>
    </div>
    {/if}
</form>


<script>
import categories from './stores/categories';

let title= '';

function addCategoryAndClear(){
    categories.addCategory(title);
    title = '';
}

</script>
