// CH Svelte/src/App.svelte
<div class="container">
  <h1>Notes Application</h1>
  <div class="row">
    <div class="col-3">
      <CategoryList />
      <NewCategory />
    </div>
    <div class="col-9">
      <Board /> 
    </div>     
  </div>
</div>

<script>
import CategoryList from './CategoryList.svelte';
import NewCategory from './NewCategory.svelte';
import Board from './Board.svelte';
</script>

// CH Redux/src/App.jsx
import React from 'react';
import CategoryList from './category/CategoryList';
import NewCategory from './category/NewCategory';
import Board from './note/Board';

import 'bootstrap/dist/css/bootstrap.css';
import './App.css'

function App() {
  return (
    <div className="container">
      <h1>Notes Application</h1>
      <div className="row">
        <div className="col-3">
          <CategoryList />
          <NewCategory />
        </div>
        <div className="col-9">
          <Board  /> 
        </div>
      </div>
    </div>
  );
}

export default App;
