// CH Redux/src/note/Board.jsx
import React from 'react';
import { connect } from 'react-redux';

import selectors from './selectors';
import actions from './actions';
import Note from './Note';
import NoteEdit from './EditNote';

function Board({notes, openCreateNote}) {
    
  return (
    <div>
      <div className="row">
        <div className="col">
          <button 
            type="button"
            className="btn btn-primary"
            onClick={openCreateNote}>
              Add
          </button>
        </div>  
      </div>

      <div className="row">
        {notes.map(note => 
          <Note note={note} key={note.id} />)}
      </div>  

      <NoteEdit />
    </div>
  );
}

//Connect
export default connect(
  state => ({
      notes: selectors.getNotes(state)
  }), {
    ...actions
  }
)(Board);

// CH Vue/src/components/Board.vue
<template>
    <div>
      <div class="row">
        <button 
         type="button"
         class="btn btn-primary" 
         @click="openCreateNote">
          Add
        </button>
      </div>
      <EditNote />
      <div class="row">
        <Note 
         v-for="note in notes" 
         :note="note" 
         :key="note.id" />
      </div>
    </div>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex';

import EditNote from './EditNote';
import Note from './Note';

export default {
  computed: {
    ...mapGetters([
      'notes'
    ])
  },
  methods: {
    ...mapMutations([
        'openCreateNote'
    ])
  },
  components: {
    EditNote,
    Note
  } 
}
</script>
