// CH Redux/src/category/CategoryList.jsx
import React from 'react';
import { connect } from 'react-redux';

import actions from './actions';
import effects from './effects';

function isSelected(category, selectedCategory){
  return (category.id === selectedCategory.id)
}

function CategoryList({ 
    categories, selectedCategory, 
    deleteCategory, selectCategory }) {
  return (
    <ul className="list-group list-group-flush">
      {categories.map(category => {
        return isSelected(category, selectedCategory)
        ? <li
            key={category.id} 
            onClick={() => selectCategory(category)} 
            className="list-group-item list-group-item-primary" >
              <span>{category.name}</span>
              <button 
               type="button" 
               className="close"
               onClick={() => deleteCategory(category.id)}>
                <span aria-hidden="true">&times;</span>
              </button>
          </li>
        : <li 
            key={category.id} 
            onClick={() => selectCategory(category)} 
            className="list-group-item">
              <span>{category.name}</span>
          </li>
      })}
    </ul>
  );
}

export default connect(
  ({categories, selectedCategory}) => ({
      categories,
      selectedCategory
  }), {
    ...actions,
    ...effects
  }
)(CategoryList);

// CH Vue/src/components/CategoryList.vue
<template>
    <ul className="list-group list-group-flush">
    <template 
     v-for="category in categories" 
     :key="category.id">
      <li
        v-if="isSelectedCategory(category)"
        @click="selectCategory(category)" 
        className="list-group-item list-group-item-primary" >
          <span>{{category.name}}</span>
          <button 
            type="button" 
            className="close"
            @click="deleteCategory(category.id)">
              <span aria-hidden="true">&times;</span>
          </button>
      </li>
      <li 
       v-else
       @click="selectCategory(category)" 
       className="list-group-item">
         <span>{{category.name}}</span>
      </li>
    </template>
    </ul>    
</template>

<script>
import { mapGetters, mapActions, mapMutations } from 'vuex';

export default {
  computed: {
    ...mapGetters([
      'categories',
      'selectedCategory'
    ])
  },
  methods: {
    isSelectedCategory(category){
      return (category.id === this.selectedCategory.id)
    },
    ...mapMutations([
      'selectCategory'
    ]), 
    ...mapActions([
        'deleteCategory'
    ])
  }
}
</script>
