// CH Svelte/src/EditNote.svelte
{#if $ui.isNoteEditDialogVisible}
<div 
 class="overlay" 
 v-show="show">
    <form class="dialog">
        <div class="modal-body">
        <div class="form-group">
        <input 
            type="text" 
            bind:value={title}
            class="form-control"
        /> 
        </div>
        <div class="form-group">
        <textarea
            rows="4"
            bind:value={content}
            class="form-control" />
        </div>
        </div>
        <div class="modal-footer">             
        <button 
            type="button"
            class="btn btn-secondary"
            on:click={ui.closeCreateNote}>
            Close
        </button>         
        <button 
            type="button" 
            class="btn btn-danger"
            on:click={deleteNote}>
            Delete
        </button>              
        <button 
            type="button" 
            class="btn btn-primary"
            on:click={saveNote} >
            Save
        </button>
        </div>
    </form>
</div>
{/if}
    
<script>
import ui from './stores/ui';
import notes from './stores/note';

let  title = '';
let  content = '';

function createNote(){
    return { 
        ...$ui.selectedNote,
        title: title,
        content: content,
        categoryID : $ui.selectedCategory.id
    };
}

function deleteNote(){
    notes.deleteNote($ui.selectedNote.id);
    ui.closeCreateNote();
}

function saveNote(){
    const note = createNote();
    notes.saveNote(note);
    ui.closeCreateNote();
}

ui.subscribe(state => {
    title = state.selectedNote.title;
    content = state.selectedNote.content;
});
</script>
    
<style>
.overlay {
    width: 100%;
    height: 100%;
    position: fixed;
    top:0;
    left:0;
    background:rgba(238, 238, 238, 0.8);
}

.dialog {
    position: absolute;
    margin: auto;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    border-radius: 8px;
    width: 400px;
    height: 300px;
    z-index: 1;
    background-color: #FFF;
    padding: 8px;
}
</style>

// CH Vue/src/components/EditNote.vue
<template>
<div 
 className="overlay" 
 v-show="show">
    <form className="dialog">
        <div className="modal-body">
        <div className="form-group">
        <input 
            type="text" 
            v-model="title"
            className="form-control"
        /> 
        </div>
        <div className="form-group">
        <textarea
            rows="4" 
            v-model="content" 
            className="form-control">
        </textarea>
        </div>
        </div>
        <div className="modal-footer">             
        <button 
            type="button"
            className="btn btn-secondary"
            @click="closeCreateNote">
            Close
        </button>         
        <button 
            type="button" 
            className="btn btn-danger"
            @click="deleteNote(note.id)">
            Delete
        </button>              
        <button 
            type="button" 
            className="btn btn-primary"
            @click="saveNote(createNote())" >
            Save
        </button>
        </div>
    </form>
    </div>
</template>

<script>
import { mapGetters, mapActions, mapMutations } from 'vuex';

export default {
data(){
    return {
        title: '',
        content: ''
    }
},
computed: {
    ...mapGetters({
        note: 'selectedNote',
        show: 'isNoteEditDialogVisible',
        category: 'selectedCategory'
    })
},
methods: {
    ...mapActions([
        'saveNote',
        'deleteNote'
    ]),
    ...mapMutations([
        'closeCreateNote'
    ]),
    createNote(){
        return { 
            ...this.note,
            title: this.title,
            content: this.content,
            categoryID : this.category.id
        };
    }    
},
watch: {
    note(){
        this.title = this.note.title;
        this.content = this.note.content;  
    }
  }
}
</script>

<style>
.overlay {
  width: 100%;
  height: 100%;
  position: fixed;
  top:0;
  left:0;
  background:rgba(238, 238, 238, 0.8);
}

.dialog {
  position: absolute;
  margin: auto;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  border-radius: 8px;
  width: 400px;
  height: 300px;
  z-index: 1;
  background-color: #FFF;
  padding: 8px;
}
</style>
